version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8000:80"
      - "4430:443"
    depends_on:
      - app

  tor:
    build:
      context: .docker/tor
      dockerfile: Dockerfile
    depends_on:
      - nginx
