version: '3'
services:
  ma_sonpike:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000

  nginx_proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ma_sonpike
