version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    expose:
      - 3000

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  tor:
    build:
      context: .docker/tor
      dockerfile: Dockerfile
    depends_on:
      - nginx
