version: '3'
services:
  ma_sonpike:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - sonpike

networks:
  sonpike:
    external: true
