on:
  push:
    branches: [ dev, main ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [ stable, beta, nightly ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
